"""Centralized configuration defaults for the FLSpam project."""

# Adversarial Training Defaults
DEFAULT_ADVERSARIAL_ROUNDS = [8, 15]
DEFAULT_ADVERSARIAL_EPISODES = 4000
DEFAULT_ADVERSARIAL_SAMPLES = 500
DEFAULT_SFT_EPOCHS = 3

# FL Defaults
DEFAULT_NUM_ROUNDS = 15
DEFAULT_FRACTION_TRAIN = 0.2
DEFAULT_LOCAL_EPOCHS = 2
DEFAULT_BATCH_SIZE = 32
DEFAULT_SPAM_STRATEGY = "iid"
DEFAULT_SPAM_ALPHA = 0.5
